services:

  wordpress:
    image: arm64v8/wordpress:5-php7.4-apache
    ports:
        - 8080:80
    environment:
        WORDPRESS_DB_HOST: mysql
        WORDPRESS_DB_USER: root
        WORDPRESS_DB_PASSWORD: root
        WORDPRESS_DB_NAME: wordpress
    links:
        - mysql:mysql

  mysql:
    platform: linux/x86_64/v8
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_DATABASE: wordpress
        MYSQL_ROOT_PASSWORD: root

